# action.yml
name: 'Deploy Single Page Application on Cloud'
description: 'Allows automated deployment of your single page application into the cloud on a server or on cloud storage via Github Actions.'
author: 'Janfabian Fabriczek <janfabian@fabriczek.engineer>'
branding:
  icon: cloud
  color: yellow
inputs:
outputs:
runs:
  using: 'docker'
  image: 'Dockerfile'
